config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }



end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :user_id, scope: :book_id

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_back(fallback_location: root_path)
    # redirect_to request.referer
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_back(fallback_location: root_path)
    # redirect_to request.referer
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def index
      @books = Book.all
      @book = Book.new
    end

    def show
      @books = Book.find(params[:id])
      @book = Book.new
      @user = User.find(@books.user_id)
      @book_comments = BookComment.all
      @book_comment = BookComment.new
    end

    def new
      @book = Book.new
    end

    def create
      @book = Book.new(book_params)
      @book.user_id = current_user.id
      if @book.save
        redirect_to book_path(@book), notice:'You have created book successfully.'
      else
        @books = Book.all
        render :index
      end
    end

    def edit
      if Book.find(params[:id]).user_id == current_user.id
        @book = Book.find(params[:id])
      else
        redirect_to books_path
      end
    end

    def update
      @book = Book.find(params[:id])
      if @book.update(book_params)
        redirect_to book_path(@book.id), notice:'You have updated book successfully.'
      else
        render :edit
      end
    end

    def destroy
      book = Book.find(params[:id])
      book.destroy
      redirect_to books_path
    end

    private
    def book_params
      params.require(:book).permit(:title, :body)
    end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.all
  end

  def edit
    if User.find(params[:id]).id == current_user.id
      @user = User.find(params[:id])
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice:'You have updated user successfully.'
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_sideset.html.erb
<div class="col-md-3">
  <h2>User Info</h2>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpeg" %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>

  <h2 class="mt-3">New book</h2>
  <%= form_with model:book, local:true do |f| %>
    <label for="titleForm">Title</label>
    <span><%= f.text_field :title,  class:"form-control", id:"titleForm" %></span>
    <label for="bodyForm">Option</label>
    <span><%= f.text_area :body, class:"form-control", id:"bodyForm" %></span>
    <%= f.submit 'Create Book', class:"btn btn-success mt-3" %>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

        <% if @book.errors.any? %>
          <div class="error-box text-danger">
            <h3 class="error-num">
              <%= @book.errors.count %>
              <% if @book.errors.count == 1 %> error <% else %> errors <% end %> prohibited this obj from being saved:
            </h3>
            <% @book.errors.full_messages.each do |message| %>
              <p>・<%= message %></p>
            <% end %>
          </div>
        <% end %>

      <%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
          <label for="titleForm">Title</label>
          <span><%= f.text_field :title, class:"form-control", id:"titleForm" %></span>
        </div>
        <div class="form-group">
          <label for="bodyForm">Option</label>
          <span><%= f.text_area :body, class:"form-control", id:"bodyForm" %></span>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class:"btn btn-success" %>
        </div>
        <p>
          <%= link_to "Show", book_path(@book) %>
          <span>|</span>
          <%= link_to "Back", books_path %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <div class="error-box text-danger">
      <h3 class="error-num">
        <%= @book.errors.count %>
        <% if @book.errors.count == 1 %> error <% else %> errors <% end %> prohibited this obj from being saved:
      </h3>
      <% @book.errors.full_messages.each do |message| %>
        <p>・<%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="row">
    <%= render 'books/sideset', user: current_user, book: @book %>

     <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th style="width:5%"></th>
            <th style="width:20%">Title</th>
            <th style="width:50%">Option</th>
            <th style="width:5%"></th>
            <th style="width:20%"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
                <% end %>
              </td>
              <td><%= link_to  book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user)%>
                  <%= link_to book.favorites.count, book_favorites_path(book), class: 'fas fa-heart text-danger', method: :delete %>
                <% else %>
                  <%= link_to book.favorites.count, book_favorites_path(book), class: 'fas fa-heart', method: :post %>
                <% end %>
              </td>
              <td>
                コメント数: <%= book.book_comments.count %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/sideset', user: @user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-inverse">
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag @books.user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
              <br />
              <%= link_to @books.user.name, user_path(@books.user_id) %>
            </td>
            <td><%= link_to @books.title, book_path(@books.id) %></td>
            <td><%= @books.body %></td>
            <td>
                <% if @books.favorited_by?(current_user)%>
                  <%= link_to @books.favorites.count, book_favorites_path(@books.id), class: 'fas fa-heart text-danger', method: :delete %>
                <% else %>
                  <%= link_to @books.favorites.count, book_favorites_path(@books.id), class: 'fas fa-heart', method: :post %>
                <% end %>
            </td>
            <td>
              コメント数: <%= @books.book_comments.count %>
            </td>
            <% if @books.user_id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@books.id), class:"btn btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@books.id), class:"btn btn-danger", method: :delete, "data-confirm" => "本当に削除しますか？"%></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <table>
        <tbody>
          <% @book_comments.each do |book_comment| %>
            <% if book_comment.book_id == @books.id %>
              <tr>
                <td>
                  <%= attachment_image_tag book_comment.user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
                  <br />
                  <%= link_to book_comment.user.name, user_path(book_comment.user_id) %>
                </td>
                <td>
                  <%= book_comment.comment %>
                </td>
                <% if book_comment.user_id == current_user.id %>
                  <td>
                    <%= link_to "Destroy", book_book_comment_path(book_comment.book_id, book_comment), class: "btn btn-danger btn-sm", method: :delete %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <%= form_with(model:[@books, @book_comment], local: true) do |f| %>
        <%= f.text_area :comment, rows:'5', class: "form-control" %>
        <%= f.submit "送信", class: "mt-2" %>
      <% end %>

    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers!</strong>
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers!!</strong></h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3" %>
        </div>
        <div class="row">
          <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-success btn-sm btn-block mb-3" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/66400954fb.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="bg-dark">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
          <a class="navbar-brand p-1 text-white" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to ' Home', user_path(current_user.id), class: 'nav-link fas fa-home text-light' %>
                </li>
                <li>
                    <%= link_to ' Users', users_path, class: 'nav-link fas fa-users text-light' %>
                </li>
                <li>
                  <%= link_to ' Books', books_path, class: 'nav-link fas fa-book-open text-light' %>
                </li>
                <li>
                  <%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'nav-link fas fa-sign-out-alt text-light' %>
                </li>
              <% else %>
                <li>
                  <%= link_to " Home", "/", class: 'nav-link fas fa-home text-light' %>
                </li>
                <li>
                  <%= link_to ' About', home_about_path, class: 'nav-link fas fa-link text-light' %>
                </li>
                <li>
                  <%= link_to ' sign up', new_user_registration_path, class: 'nav-link fas fa-user-plus text-light' %>
                </li>
                <li>
                  <%= link_to ' login', new_user_session_path, class: 'nav-link fas fa-sign-in-alt text-light' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <p class="notice text-success"><%= flash[:notice] %></p>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <% if @user.errors.any? %>
        <div class="error-box text-danger">
          <h3 class="error-num">
            <%= @user.errors.count %>
            <% if @user.errors.count == 1 %> error <% else %> errors <% end %> prohibited this obj from being saved:
          </h3>
          <% @user.errors.full_messages.each do |message| %>
            <p>・<%= message %></p>
          <% end %>
        </div>
      <% end %>

      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <label for="nameForm">Name</label>
          <%= f.text_field :name, class:"form-control", id:"nameForm" %>
        </div>
        <div class="form-group">
          <label for="imageForm">Image</label>
          <%= f.attachment_field :profile_image, class:"form-control-file", id:"imageForm" %>
        </div>
        <div class="form-group">
          <label for="introductionForm">Introduction</label>
          <%= f.text_area :introduction, class:"form-control", id:"introductionForm" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class:"btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/sideset', user: current_user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-inverse">
        <thead>
          <th>image</th>
          <th>name</th>
          <th></th>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, fallback: "no_image", size: "40x40" %></td>
              <td><%= user.name %></td>
              <td><%= link_to 'Show', user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'books/sideset', user: @user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <th></th>
          <th>Title</th>
          <th>Option</th>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <% if book.user_id == @user.id %>
              <tr>
                <td>
                  <%= link_to user_path(book.user_id) do %>
                    <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpeg", size: "40x40" %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book) %></td>
                <td><%= book.body %></td>
                <td>
                <% if book.favorited_by?(current_user)%>
                  <%= link_to book.favorites.count, book_favorites_path(book), class: 'fas fa-heart text-danger', method: :delete %>
                <% else %>
                  <%= link_to book.favorites.count, book_favorites_path(book), class: 'fas fa-heart', method: :post %>
                <% end %>
              </td>
                <td>
                コメント数: <%= book.book_comments.count %>
              </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>